[package]
name = "richard_fib_rs"
version = "0.1.0"
authors = ["Richard Chukwu <richinex@gmail.com>"]
edition = "2018"

[dependencies]
pyo3 = { version = "0.20.2", features = ["extension-module"] }

[lib]
name = "richard_fib_rs"
crate-type = ["cdylib"]

path = "src/lib.rs"