[project]
name = "richard-fib-rs"
version = "0.1"
description = "A description for your project"
authors = [
    { name = "Richard Chukwu", email = "richinex@example.com" }
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
]

[tool.setuptools.packages]
# Pure Python packages/modules
find = { where = ["python"] }


[[tool.setuptools-rust.ext-modules]]
# Private Rust extension module to be nested into the Python package
target = "richard_fib_rs.richard_fib_rs"  # The last part of the name (e.g. "_lib") has to match lib.name in Cargo.toml,
                             # but you can add a prefix to nest it inside of a Python package.
path = "Cargo.toml"      # Default value, can be omitted
binding = "PyO3"