[build-system]
requires = ["setuptools>=42", "wheel", "setuptools_rust"]

[project]
name = "richard-fib-rs"
version = "0.1"
description = "A Python package with Rust extensions."
authors = [{name = "Richard", email = "richinex@example.com"}]
requires-python = ">=3.9"
license = "MIT"
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python",
    "Programming Language :: Rust",
    "Operating System :: POSIX",
    "Operating System :: MacOS :: MacOS X",
]
dependencies = []
